# Generated by Django 6.0.7 on 2026-07-30 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set automatically on first publish; set a future date to schedule.', null=True)),
                ('seo_title', models.CharField(blank=True, help_text='≤60 chars ideal. Falls back to the title.', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='≤155 chars ideal. Falls back to the excerpt/summary.', max_length=170)),
                ('canonical_url', models.URLField(blank=True, help_text='Only when this content is republished from elsewhere.')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.CharField(help_text='Short summary shown in lists; meta description fallback.', max_length=300)),
                ('body', models.TextField(help_text='Markdown.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('cover_image_alt', models.CharField(blank=True, max_length=200)),
                ('reading_minutes', models.PositiveSmallIntegerField(default=0, help_text='0 = computed automatically from the body on save.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
