# Generated by Django 6.0.7 on 2026-07-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set automatically on first publish; set a future date to schedule.', null=True)),
                ('seo_title', models.CharField(blank=True, help_text='≤60 chars ideal. Falls back to the title.', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='≤155 chars ideal. Falls back to the excerpt/summary.', max_length=170)),
                ('canonical_url', models.URLField(blank=True, help_text='Only when this content is republished from elsewhere.')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tag', models.CharField(help_text='Industry badge shown on cards, e.g. "Healthcare".', max_length=60)),
                ('summary', models.CharField(help_text='Card text + meta description fallback.', max_length=300)),
                ('body', models.TextField(help_text='Markdown. Suggested sections: Problem, Architecture, Trade-offs, Outcomes.')),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='Chips on the card, e.g. ["Laravel", "PostgreSQL"].')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='case-studies/')),
                ('cover_image_alt', models.CharField(blank=True, max_length=200)),
                ('featured', models.BooleanField(default=False, help_text='Featured cards appear on the home page.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'case studies',
                'ordering': ['sort_order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('architecture', 'Architecture (layers)'), ('code', 'Code (brackets)'), ('integration', 'Integration (pulse)'), ('ai', 'AI (robot)')], default='code', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Referenced by the frontend, e.g. "hero_headline". Renaming breaks the reference.', max_length=100, unique=True)),
                ('value', models.TextField()),
                ('note', models.CharField(blank=True, help_text='Where this text appears (for your future self).', max_length=200)),
            ],
            options={
                'verbose_name': 'site text',
                'verbose_name_plural': 'site texts',
                'ordering': ['key'],
            },
        ),
    ]
