# Generated by Django 6.0.7 on 2026-07-30 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube link (watch/share/shorts URL) — embedded on the detail page.'),
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='case-studies/gallery/')),
                ('alt', models.CharField(blank=True, help_text='Describe the screenshot for SEO/accessibility.', max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.casestudy')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
